// <auto-generated />
namespace SIVU_OLIVIU_ID_IE_PROIECT_MP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class createModels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createModels));
        
        string IMigrationMetadata.Id
        {
            get { return "202012221619385_createModels"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
